"""empty message

Revision ID: 876eda121406
Revises: 539b31a758cb
Create Date: 2020-09-22 01:23:13.631407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876eda121406'
down_revision = '539b31a758cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('artist_genre', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artist_genre', 'genre', ['genre_id'], ['id'])
    op.add_column('venue_genre', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue_genre', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genre', type_='foreignkey')
    op.drop_column('venue_genre', 'genre_id')
    op.drop_constraint(None, 'artist_genre', type_='foreignkey')
    op.drop_column('artist_genre', 'genre_id')
    op.drop_table('genre')
    # ### end Alembic commands ###
